### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by moudhamam** [xang1234/Finviz-Scraper#1]
Implementing exactly the Finviz-Scraper.py code in Jupyter Notebook returns the following error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-a370fc425f19> in <module>
----> 1 data=scrape_finviz(['FB','INGN','BABA','RMD','GOOS'])
      2 print(data)

<ipython-input-2-268abb2af018> in scrape_finviz(symbols)
      4     soup = BeautifulSoup(req.content, 'html.parser')
      5     table = soup.find_all(lambda tag: tag.name=='table')
----> 6     rows = table[8].findAll(lambda tag: tag.name=='tr')
      7     out=[]
      8     for i in range(len(rows)):

IndexError: list index out of range

**Comment by MelnNik** [comment]
Hello, did you manage to fix this?

**Comment by moudhamam** [comment]
> Hello, did you manage to fix this?

Nope. I used a different method to scrape Finviz using Google Sheets instead.

**Comment by xang1234** [comment]
updated the script to handle website changes
